name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build
        run: make build
      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: '${{ secrets.REMOTE_SSH_KEY }}'
      - name: Deploy
        run: make deploy
        env:
          REMOTE_USER: '${{ secrets.REMOTE_USER }}'
          REMOTE_HOST: '${{ secrets.REMOTE_HOST }}'
          REMOTE_PORT: '${{ secrets.REMOTE_PORT }}'
          REMOTE_DIR: '${{ secrets.REMOTE_DIR }}'
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
